[versions]
kotest = "5.9.1"
mockito = "5.12.0"
kotlin = "2.0.0"
ktlint = "10.3.0"
log4j = "2.20.0"
archunit-version = "1.3.0"
vertx = "4.4.5"
jackson = "2.13.4.2"
typescript-gradle-plugin-version = "4.3.5"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
archunit = { module = "com.tngtech.archunit:archunit", version.ref = "archunit-version" }
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertx" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-web-client = { module = "io.vertx:vertx-web-client", version.ref = "vertx" }
vertx-kafka-client = { module = "io.vertx:vertx-kafka-client", version.ref = "vertx" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-databind", version = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version = "jackson" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
dokka = "org.jetbrains.dokka:1.9.20"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.7" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
typescript-gradle-plugin = { id = "io.github.zucchero-sintattico.typescript-gradle-plugin", version.ref = "typescript-gradle-plugin-version" }
